require 'tmpdir'
require 'erb'
require 'git'
require 'rush'
require 'fileutils'
require 'right_aws'
require File.dirname(__FILE__) + '/gaffer/base'
require File.dirname(__FILE__) + '/gaffer/deb'
require File.dirname(__FILE__) + '/gaffer/repro'
